### ISSUE TITLE
Header links don't go to phoenix routes

### ISSUE THREAD

**Issue by colonelpopcorn** [ryanwinchester/mixdown#2]
The nav links on the header template are pointing to html files instead of Phoenix routes. Is this the intended behavior?

![issue1](https://cloud.githubusercontent.com/assets/13068221/24683802/6d4058b0-196f-11e7-84c8-a94428f4f77c.png)
![issue2](https://cloud.githubusercontent.com/assets/13068221/24683801/6d3e6bfe-196f-11e7-8304-40df3e3dc039.png)

**Comment by ryanwinchester** [comment]
No. The template is incomplete. wait 'til you see the admin side.

**Comment by ryanwinchester** [comment]
they do now 😂
